// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.0'
        classpath 'com.google.gms:google-services:4.4.4'
    }
}

apply from: "variables.gradle"

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://maven.google.com'
        }
        maven {
            url 'https://jitpack.io'
        }
    }
}

subprojects {
    afterEvaluate { project ->
        if (project.hasProperty('android')) {
            project.android {
                if (project.android.hasProperty('compileSdkVersion')) {
                    compileSdkVersion 36
                }
                if (project.android.hasProperty('buildToolsVersion')) {
                    buildToolsVersion '36.0.0'
                }
                if (project.android.hasProperty('defaultConfig')) {
                    project.android.defaultConfig {
                        minSdkVersion 26
                        targetSdkVersion 36
                    }
                }
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}